# load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "ntirpc",
    hdrs = glob(["*.h"]),
    strip_include_prefix = "//ntirpc/ntirpc",
)
